const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const KEY="juda_v5_state";
const catalog=[
["Жим штанги лёжа","Грудь","Базовое"],["Приседания со штангой","Ноги","Базовое"],["Тяга верхнего блока","Спина","Базовое"],["Разводка гантелей лёжа","Грудь","Изолирующее"],["Подтягивания","Спина","Базовое"],["Жим гантелей сидя","Плечи","Базовое"],["Выпады с гантелями","Ноги","Базовое"],["Разгибание рук на блоке","Руки","Изолирующее"],["Сгибание рук с гантелями","Руки","Изолирующее"],["Румынская тяга","Ноги","Базовое"]
];
const starter={id:"p1",name:"Силовая база",daysPerWeek:4,weeks:8,active:true,days:[
{name:"Верх тела",exercises:[{name:"Жим штанги лёжа",sets:3,reps:8,weight:60,rest:90},{name:"Тяга верхнего блока",sets:3,reps:10,weight:45,rest:90},{name:"Жим гантелей сидя",sets:3,reps:10,weight:18,rest:90}]},
{name:"Низ тела",exercises:[{name:"Приседания со штангой",sets:3,reps:8,weight:70,rest:120}]},
{name:"Спина + плечи",exercises:[{name:"Подтягивания",sets:3,reps:8,weight:0,rest:90}]},
{name:"Лёгкая тренировка",exercises:[]}]};
let state=load(),tab="home",editingProgram=null,editingDay=0,activeWorkout=null,restTimer=null,restRemaining=0;
function load(){try{let x=JSON.parse(localStorage.getItem(KEY));if(x)return x}catch(e){}return{programs:[starter],history:[]}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function p(){return state.programs.find(x=>x.active)||state.programs[0]}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function fmt(n){return new Intl.NumberFormat("ru-RU").format(Math.round(n||0))}
function toast(t){let e=$("#toast");e.textContent=t;e.classList.remove("hidden");clearTimeout(window.tt);window.tt=setTimeout(()=>e.classList.add("hidden"),2200)}
function render(){let titles={home:"Главная",workouts:"Тренировки",food:"Питание",progress:"Прогресс"};$("#pageTitle").textContent=titles[tab]||"Тренировка";$$(".nav-item").forEach(x=>x.classList.toggle("active",x.dataset.tab===tab));({home:home,workouts:workouts,food:food,progress:progress}[tab])()}
function home(){let q=p(),d=q.days.find(x=>x.exercises.length);$("#app").innerHTML=`<section class="hero"><span class="tag">ТВОЙ ПЛАН</span><h2>${esc(q.name)}</h2><p>${q.daysPerWeek} тренировки в неделю · ${q.weeks} недель</p><button class="primary-btn" id="start">${d?"Начать тренировку":"Добавить упражнения"}</button></section><section class="section"><div class="section-head"><h2>Ближайшая тренировка</h2><span>${d?esc(d.name):"Пусто"}</span></div><div class="card">${d?d.exercises.map((e,i)=>`<div class="exercise-row"><div class="exercise-icon">${["◈","△","◇","○"][i%4]}</div><div class="grow"><b>${esc(e.name)}</b><small>${e.sets} × ${e.reps} · ${e.weight||0} кг</small></div></div>`).join(""):`<div class="empty">Добавь упражнения в конструкторе.</div>`}</div></section><section class="section"><div class="grid2"><div class="card stat"><span class="muted">Тренировок</span><strong>${state.history.length}</strong></div><div class="card stat"><span class="muted">Объём</span><strong>${fmt(state.history.reduce((a,w)=>a+w.volume,0))} кг</strong></div></div></section>`;$("#start").onclick=()=>d?startWorkout(q.days.indexOf(d)):editProgram()}
function workouts(){let q=p();$("#app").innerHTML=`<section class="section" style="margin-top:0"><div class="row"><div><h2>${esc(q.name)}</h2><div class="muted">${q.daysPerWeek} тренировок / неделю</div></div><button class="ghost-btn" id="newProgram">+ Программа</button></div></section><section class="section"><div class="stack">${q.days.map((d,i)=>`<div class="card"><div class="row"><div><b>День ${i+1} · ${esc(d.name)}</b><div class="muted">${d.exercises.length} упражнений</div></div><div><button class="small-btn editDay" data-i="${i}">Изменить</button> <button class="primary-btn startDay" data-i="${i}" style="width:auto;margin:0;padding:9px 11px">Старт</button></div></div>${d.exercises.slice(0,4).map(e=>`<div class="exercise-row"><div class="exercise-icon">◈</div><div class="grow"><b>${esc(e.name)}</b><small>${e.sets} × ${e.reps}${e.weight?` · ${e.weight} кг`:""}</small></div></div>`).join("")}</div>`).join("")}</div></section><section class="section"><button class="primary-btn" id="editProgram">Настройки программы</button></section>`;$$(".startDay").forEach(b=>b.onclick=()=>startWorkout(+b.dataset.i));$$(".editDay").forEach(b=>b.onclick=()=>editDay(+b.dataset.i));$("#editProgram").onclick=editProgram;$("#newProgram").onclick=newProgram}
function food(){$("#app").innerHTML=`<section class="hero"><span class="tag">СЛЕДУЮЩИЙ МОДУЛЬ</span><h2>Питание</h2><p>Калории, БЖУ и дневник еды добавим после завершения основных тренировочных функций.</p></section>`}
function progress(){let vol=state.history.reduce((a,w)=>a+w.volume,0);$("#app").innerHTML=`<div class="grid2"><div class="card stat"><span class="muted">Тренировок</span><strong>${state.history.length}</strong></div><div class="card stat"><span class="muted">Объём</span><strong>${fmt(vol)} кг</strong></div></div><section class="section"><div class="section-head"><h2>История</h2></div><div class="stack">${state.history.length?state.history.map(w=>`<div class="card history-item"><div><b>${esc(w.name)}</b><div class="muted">${w.date} · ${w.completedSets} подходов</div></div><b class="blue">${fmt(w.volume)} кг</b></div>`).join(""):`<div class="card empty">История появится после тренировки.</div>`}</div></section>`}
function startWorkout(i=0){let q=p(),d=q.days[i]||q.days.find(x=>x.exercises.length);if(!d?.exercises.length){toast("В этом дне нет упражнений");return}activeWorkout={dayName:d.name,dayIndex:q.days.indexOf(d),exercises:d.exercises.map(e=>({...e,done:Array(+e.sets||1).fill(false)})),current:0};showWorkout()}
function showWorkout(){let e=activeWorkout?.exercises[activeWorkout.current];if(!e){finishWorkout();return}let done=e.done.filter(Boolean).length,total=activeWorkout.exercises.reduce((a,x)=>a+x.done.length,0),all=activeWorkout.exercises.reduce((a,x)=>a+x.done.filter(Boolean).length,0);$("#pageTitle").textContent="Активная тренировка";$$(".nav-item").forEach(x=>x.classList.remove("active"));$("#app").innerHTML=`<section class="hero"><div class="row"><span class="muted">${esc(activeWorkout.dayName)}</span><span class="blue">${activeWorkout.current+1}/${activeWorkout.exercises.length}</span></div><div class="progress" style="margin-top:13px"><i style="width:${Math.round(all/total*100)}%"></i></div><h2 style="margin-top:15px">${esc(e.name)}</h2><p style="margin-top:6px">Цель: ${e.reps} повторений · ${e.weight||0} кг</p></section><section class="section"><div class="section-head"><h2>Подходы</h2><span>${done}/${e.sets}</span></div><div class="sets">${e.done.map((d,i)=>`<button class="set-btn ${d?"done":""}" data-set="${i}"><span class="num">${i+1}</span><span><b>${e.weight||0} кг</b><br><small class="muted">вес</small></span><span><b>${e.reps}</b><br><small class="muted">повт.</small></span><span class="check">${d?"✓":"○"}</span></button>`).join("")}</div><div class="workout-actions"><button class="ghost-btn" id="editCurrent">Изменить</button><button class="primary-btn" id="next" style="margin:0">${done===e.sets?"Следующее":"Пропустить"}</button></div></section><section class="section"><div class="card"><div class="row"><div><b>Отдых</b><div class="muted">Таймер запускается после подхода</div></div><b id="timer">${time(restRemaining)}</b></div><div class="workout-actions"><button class="ghost-btn" id="timerBtn">${restTimer?"Пауза":"Старт 90 сек"}</button><button class="ghost-btn" id="resetTimer">Сброс</button></div></div></section><section class="section"><button class="danger-btn" id="finish" style="width:100%">Завершить тренировку</button></section>`;$$(".set-btn").forEach(b=>b.onclick=()=>toggleSet(+b.dataset.set));$("#next").onclick=()=>{activeWorkout.current++;showWorkout()};$("#editCurrent").onclick=editCurrent;$("#finish").onclick=finishWorkout;$("#timerBtn").onclick=toggleTimer;$("#resetTimer").onclick=()=>{stopTimer();restRemaining=0;showWorkout()}}
function toggleSet(i){let e=activeWorkout.exercises[activeWorkout.current];e.done[i]=!e.done[i];if(e.done[i]){restRemaining=+e.rest||90;startTimer()}else showWorkout()}
function time(s){return `${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`}
function startTimer(){clearInterval(restTimer);restTimer=setInterval(()=>{restRemaining--;let t=$("#timer");if(t)t.textContent=time(Math.max(0,restRemaining));if(restRemaining<=0){stopTimer();toast("Отдых закончен")}},1000);showWorkout()}
function stopTimer(){clearInterval(restTimer);restTimer=null}
function toggleTimer(){if(restTimer){stopTimer();showWorkout()}else{if(!restRemaining)restRemaining=90;startTimer()}}
function finishWorkout(){if(!activeWorkout)return;stopTimer();let records=[];activeWorkout.exercises.forEach(e=>e.done.forEach((d,i)=>d&&records.push({exercise:e.name,weight:+e.weight||0,reps:+e.reps||0,set:i+1})));state.history.unshift({id:Date.now(),name:activeWorkout.dayName,date:new Date().toLocaleString("ru-RU",{day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit"}),completedSets:records.length,volume:records.reduce((a,r)=>a+r.weight*r.reps,0),records});save();activeWorkout=null;restRemaining=0;tab="progress";render();toast("Тренировка сохранена")}
function editCurrent(){let e=activeWorkout.exercises[activeWorkout.current];openModal(`<h2>${esc(e.name)}</h2><div class="form"><label>Вес, кг<input id="w" type="number" min="0" step=".5" value="${e.weight||0}"></label><label>Повторения<input id="r" type="number" min="1" value="${e.reps}"></label><label>Отдых, сек<input id="rest" type="number" min="0" value="${e.rest||90}"></label><button class="primary-btn" id="saveE">Сохранить</button></div>`);$("#saveE").onclick=()=>{e.weight=+$("#w").value;e.reps=+$("#r").value;e.rest=+$("#rest").value;closeModal();showWorkout()}}
function editProgram(){let q=p();openModal(`<h2>Настройки программы</h2><div class="form"><label>Название<input id="pn" value="${esc(q.name)}"></label><label>Тренировок в неделю<input id="pd" type="number" min="1" max="7" value="${q.daysPerWeek}"></label><label>Длительность, недель<input id="pw" type="number" min="1" max="52" value="${q.weeks}"></label><button class="primary-btn" id="sp">Сохранить</button></div>`);$("#sp").onclick=()=>{q.name=$("#pn").value.trim()||"Моя программа";q.daysPerWeek=Math.max(1,+$("#pd").value||4);q.weeks=Math.max(1,+$("#pw").value||8);while(q.days.length<q.daysPerWeek)q.days.push({name:`День ${q.days.length+1}`,exercises:[]});q.days=q.days.slice(0,q.daysPerWeek);save();closeModal();render()}}
function editDay(i){editingDay=i;let q=p(),d=q.days[i];openDayEditor(d)}
function openDayEditor(d){editingProgram=p();let ex=d.exercises;openModal(`<h2>День тренировки</h2><div class="form"><label>Название дня<input id="dn" value="${esc(d.name)}"></label><div class="day-editor"><div class="row"><b>Упражнения</b><button class="small-btn" id="addEx">+ Добавить</button></div><div id="dayList" style="margin-top:8px">${ex.map((e,i)=>exerciseEditor(e,i)).join("")||`<div class="empty">Пока нет упражнений</div>`}</div></div><button class="primary-btn" id="saveDay">Сохранить день</button></div>`);$("#addEx").onclick=()=>openPicker();$("#saveDay").onclick=saveDay}
function exerciseEditor(e,i){return `<div class="day-ex" data-ex="${i}"><div class="grow"><b>${esc(e.name)}</b><div class="field-row"><input class="es" type="number" min="1" value="${e.sets}" title="Подходы"><input class="er" type="number" min="1" value="${e.reps}" title="Повторы"><input class="ew" type="number" min="0" step=".5" value="${e.weight||0}" title="Вес"></div></div><button class="icon-action removeEx" data-i="${i}">×</button></div>`}
function saveDay(){let q=editingProgram,d=q.days[editingDay];d.name=$("#dn").value.trim()||`День ${editingDay+1}`;$$(".day-ex").forEach((row,i)=>{if(!d.exercises[i])return;d.exercises[i].sets=Math.max(1,+row.querySelector(".es").value||1);d.exercises[i].reps=Math.max(1,+row.querySelector(".er").value||1);d.exercises[i].weight=Math.max(0,+row.querySelector(".ew").value||0)});save();closeModal();render()}
function openPicker(){let d=editingProgram.days[editingDay];openModal(`<h2>Добавить упражнение</h2><input class="form search" id="searchEx" placeholder="Поиск упражнения..."><div id="picker">${catalog.map((e,i)=>pickerItem(e,i)).join("")}</div>`);bindPicker();$("#searchEx").oninput=bindPicker}
function pickerItem(e,i){return `<div class="picker-item" data-name="${esc(e[0].toLowerCase())}"><div><b>${esc(e[0])}</b><div class="muted">${esc(e[1])} · ${esc(e[2])}</div></div><button class="small-btn addPick" data-i="${i}">Добавить</button></div>`}
function bindPicker(){let q=($("#searchEx")?.value||"").toLowerCase();$$(".picker-item").forEach(x=>x.style.display=x.dataset.name.includes(q)?"flex":"none");$$(".addPick").forEach(b=>b.onclick=()=>{let e=catalog[+b.dataset.i];editingProgram.days[editingDay].exercises.push({name:e[0],sets:3,reps:10,weight:0,rest:90});openDayEditor(editingProgram.days[editingDay])})}
function newProgram(){let id="p"+Date.now(),q={id,name:"Новая программа",daysPerWeek:3,weeks:8,active:false,days:[{name:"День 1",exercises:[]},{name:"День 2",exercises:[]},{name:"День 3",exercises:[]}]};state.programs.forEach(x=>x.active=false);q.active=true;state.programs.push(q);save();editProgram()}
function openModal(c){$("#sheet").innerHTML=c;$("#modal").classList.remove("hidden")}
function closeModal(){$("#modal").classList.add("hidden");$("#sheet").innerHTML=""}
$("#modal").onclick=e=>{if(e.target.dataset.closeModal!==undefined)closeModal()};
$("#quickAdd").onclick=()=>openModal(`<h2>Быстро добавить</h2><div class="sheet-grid"><button class="sheet-action" id="qa"><b>Тренировка</b><span>Начать текущую программу</span></button><button class="sheet-action" onclick="toast('Питание добавим следующим этапом')"><b>Еда</b><span>Дневник питания</span></button></div>`); 
$("#modal").addEventListener("click",e=>{if(e.target.id==="qa"){closeModal();tab="workouts";render();setTimeout(()=>startWorkout(),40)}});
$$(".nav-item").forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render()});
$("#headerAction").onclick=()=>toast("Профиль добавим позже");
render();